"""colonne utilisateurs.logo

Revision ID: aaed7dc90a49
Revises: b7587dce1950
Create Date: 2024-05-29 23:08:56.523786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaed7dc90a49'
down_revision: Union[str, None] = 'b7587dce1950'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateurs', sa.Column('logo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("utilisateurs") as batch_op:
        batch_op.drop_column('logo')
    # ### end Alembic commands ###
